export const AUTONOMOUS_COMMUNITIES = [
  'Andalucía',
  'Aragón',
  'Principado de Asturias',
  'Islas Baleares',
  'Canarias',
  'Cantabria',
  'Castilla-La Mancha',
  'Castilla y León',
  'Cataluña',
  'Comunitat Valenciana',
  'Extremadura',
  'Galicia',
  'La Rioja',
  'Comunidad de Madrid',
  'Región de Murcia',
  'Comunidad Foral de Navarra',
  'País Vasco',
  'Ceuta',
  'Melilla',
] as const;

export type AutonomousCommunity = (typeof AUTONOMOUS_COMMUNITIES)[number];

export const PROVINCES: string[] = [
  'Álava', 'Albacete', 'Alicante', 'Almería', 'Asturias', 'Ávila',
  'Badajoz', 'Islas Baleares', 'Barcelona', 'Burgos',
  'Cáceres', 'Cádiz', 'Cantabria', 'Castellón', 'Ciudad Real', 'Córdoba', 'Cuenca',
  'Gerona', 'Granada', 'Guadalajara', 'Guipúzcoa',
  'Huelva', 'Huesca',
  'Jaén',
  'La Coruña', 'La Rioja', 'Las Palmas', 'León', 'Lérida', 'Lugo',
  'Madrid', 'Málaga', 'Murcia',
  'Navarra',
  'Orense',
  'Palencia', 'Pontevedra',
  'Salamanca', 'Segovia', 'Sevilla', 'Soria',
  'Tarragona', 'Santa Cruz de Tenerife', 'Teruel', 'Toledo',
  'Valencia', 'Valladolid', 'Vizcaya',
  'Zamora', 'Zaragoza',
  'Ceuta', 'Melilla',
];

export const PROVINCE_TO_CCAA: Record<string, AutonomousCommunity> = {
  'Álava':                    'País Vasco',
  'Albacete':                 'Castilla-La Mancha',
  'Alicante':                 'Comunitat Valenciana',
  'Almería':                  'Andalucía',
  'Asturias':                 'Principado de Asturias',
  'Ávila':                    'Castilla y León',
  'Badajoz':                  'Extremadura',
  'Islas Baleares':           'Islas Baleares',
  'Barcelona':                'Cataluña',
  'Burgos':                   'Castilla y León',
  'Cáceres':                  'Extremadura',
  'Cádiz':                    'Andalucía',
  'Cantabria':                'Cantabria',
  'Castellón':                'Comunitat Valenciana',
  'Ciudad Real':              'Castilla-La Mancha',
  'Córdoba':                  'Andalucía',
  'Cuenca':                   'Castilla-La Mancha',
  'Gerona':                   'Cataluña',
  'Granada':                  'Andalucía',
  'Guadalajara':              'Castilla-La Mancha',
  'Guipúzcoa':                'País Vasco',
  'Huelva':                   'Andalucía',
  'Huesca':                   'Aragón',
  'Jaén':                     'Andalucía',
  'La Coruña':                'Galicia',
  'La Rioja':                 'La Rioja',
  'Las Palmas':               'Canarias',
  'León':                     'Castilla y León',
  'Lérida':                   'Cataluña',
  'Lugo':                     'Galicia',
  'Madrid':                   'Comunidad de Madrid',
  'Málaga':                   'Andalucía',
  'Murcia':                   'Región de Murcia',
  'Navarra':                  'Comunidad Foral de Navarra',
  'Orense':                   'Galicia',
  'Palencia':                 'Castilla y León',
  'Pontevedra':               'Galicia',
  'Salamanca':                'Castilla y León',
  'Segovia':                  'Castilla y León',
  'Sevilla':                  'Andalucía',
  'Soria':                    'Castilla y León',
  'Tarragona':                'Cataluña',
  'Santa Cruz de Tenerife':   'Canarias',
  'Teruel':                   'Aragón',
  'Toledo':                   'Castilla-La Mancha',
  'Valencia':                 'Comunitat Valenciana',
  'Valladolid':               'Castilla y León',
  'Vizcaya':                  'País Vasco',
  'Zamora':                   'Castilla y León',
  'Zaragoza':                 'Aragón',
  'Ceuta':                    'Ceuta',
  'Melilla':                  'Melilla',
};
